- README.md
- package.json
- packages/libuild-plugin-babel-preset/README.md
- packages/libuild-plugin-babel-preset/package.json
- packages/libuild-plugin-babel/README.md
- packages/libuild-plugin-babel/package.json
- packages/libuild-plugin-es5/README.md
- packages/libuild-plugin-es5/package.json
- packages/libuild-plugin-node-polyfill/README.md
- packages/libuild-plugin-node-polyfill/package.json
- packages/libuild-plugin-svgr/README.md
- packages/libuild-plugin-svgr/package.json
- packages/libuild/README.md
- packages/libuild/package.json
> docs: add README for all published packages and repo

- common/changes/@modern-js/libuild-plugin-babel-preset/chore-plugin_2022-10-18-09-02.json
- common/changes/@modern-js/libuild-plugin-babel/chore-plugin_2022-10-18-09-02.json
- common/changes/@modern-js/libuild-plugin-es5/chore-plugin_2022-10-18-09-02.json
- common/changes/@modern-js/libuild-plugin-node-polyfill/chore-plugin_2022-10-18-09-02.json
- common/changes/@modern-js/libuild-plugin-svgr/chore-plugin_2022-10-18-09-02.json
- common/config/rush/pnpm-lock.yaml
- packages/libuild-plugin-babel-preset/package.json
- packages/libuild-plugin-babel/package.json
- packages/libuild-plugin-es5/libuild.config.ts
- packages/libuild-plugin-es5/package.json
- packages/libuild-plugin-node-polyfill/package.json
- packages/libuild-plugin-svgr/package.json
- rush.json
> chore: libuild plugin use remote to build

- common/changes/@modern-js/libuild/chore-error_2022-10-19-12-19.json
- packages/libuild/src/cli.ts
- packages/libuild/src/core/index.ts
- packages/libuild/src/error/failure.ts
- packages/libuild/src/error/index.ts
- packages/libuild/src/error/utils.ts
- packages/libuild/src/types/builder.ts
- packages/libuild/src/types/error.ts
- packages/libuild/test/dts/exist.test-d.ts
- tests/errors/src/errors.test.ts
> refactor: refactor error thrown by libuilder

- common/changes/@modern-js/libuild/fix-async-compile-style_2022-10-21-12-33.json
- packages/libuild/src/bundler/index.ts
> fix: add `await` for style compile

- .github/workflows/CI.yml
- .github/workflows/release.yml
- .nvmrc
> chore: update ci node-version to 16

- common/changes/@modern-js/libuild/fix-win32-path_2022-11-21-08-15.json
- packages/libuild/src/plugins/asset.ts
> fix: fix win32 path in relative

- common/changes/@modern-js/libuild/fix-redirect_2022-12-23-07-46.json
- packages/libuild/src/plugins/redirect.ts
- tests/fixture/src/redirect/redirect.test.ts
> fix: replace css module filename

- common/changes/@modern-js/libuild/feat-ignore-dts-file_2023-01-16-04-16.json
- packages/libuild/src/config/normalize.ts
- tests/configs/src/__snapshots__/config.test.ts.snap
- tests/configs/src/ignore-dts-files/index.test.ts
> fix: add logic which is ignore d.ts files

- common/changes/@modern-js/libuild/main_2023-01-16-08-11.json
- packages/libuild/src/plugins/redirect.ts
- tests/fixture/src/redirect/redirect.test.ts
- tests/fixture/src/redirect/src/style.ts
> fix: fix redirect error, no redirect file which is dep

- common/changes/@modern-js/libuild-plugin-swc/main_2023-02-01-09-23.json
- packages/libuild-plugin-swc/src/es5.ts
- packages/libuild-plugin-swc/src/transform.ts
- packages/libuild-plugin-swc/src/umd.ts
> fix(libuild-plugin-swc): add isModule option

- common/changes/@modern-js/libuild-plugin-babel-preset/release-v0.11.3_2023-03-08-08-07.json
- common/changes/@modern-js/libuild-plugin-babel/release-v0.11.3_2023-03-08-08-07.json
- common/changes/@modern-js/libuild-plugin-node-polyfill/release-v0.11.3_2023-03-08-08-07.json
- common/changes/@modern-js/libuild-plugin-svgr/release-v0.11.3_2023-03-08-08-07.json
- common/changes/@modern-js/libuild-plugin-swc/release-v0.11.3_2023-03-08-08-07.json
- common/changes/@modern-js/libuild/release-v0.11.3_2023-03-08-08-07.json
- common/config/rush/version-policies.json
- packages/libuild-plugin-babel-preset/CHANGELOG.json
- packages/libuild-plugin-babel-preset/CHANGELOG.md
- packages/libuild-plugin-babel-preset/package.json
- packages/libuild-plugin-babel/CHANGELOG.json
- packages/libuild-plugin-babel/CHANGELOG.md
- packages/libuild-plugin-babel/package.json
- packages/libuild-plugin-node-polyfill/CHANGELOG.json
- packages/libuild-plugin-node-polyfill/CHANGELOG.md
- packages/libuild-plugin-node-polyfill/package.json
- packages/libuild-plugin-svgr/CHANGELOG.json
- packages/libuild-plugin-svgr/CHANGELOG.md
- packages/libuild-plugin-svgr/package.json
- packages/libuild-plugin-swc/CHANGELOG.json
- packages/libuild-plugin-swc/CHANGELOG.md
- packages/libuild-plugin-swc/package.json
- packages/libuild/CHANGELOG.json
- packages/libuild/CHANGELOG.md
- packages/libuild/package.json
> chore: bump v0.11.3

- common/changes/@modern-js/libuild-plugin-swc/feat-upgrade-swc_2023-03-10-11-05.json
- common/config/rush/pnpm-lock.yaml
- packages/libuild-plugin-swc/package.json
> chore: upgrade @modern-js/swc-plugins to 0.2.0

- common/changes/@modern-js/libuild/main_2023-03-31-08-24.json
- packages/libuild/src/config/normalize.ts
- packages/libuild/src/config/schema.ts
- packages/libuild/src/plugins/redirect.ts
- packages/libuild/src/types/config/index.ts
- tests/configs/src/__snapshots__/config.test.ts.snap
- tests/fixture/src/redirect/disable-redirect.test.ts
> feat: add redirect config

- common/changes/@modern-js/libuild-plugin-swc/feat-swc-transform_2023-04-18-08-58.json
- common/changes/@modern-js/libuild/feat-swc-transform_2023-04-18-08-58.json
- common/config/rush/pnpm-lock.yaml
- example/libuild.config.ts
- example/package.json
- example/src/bundle/lib.ts
- packages/libuild-plugin-swc/package.json
- packages/libuild-plugin-swc/src/constants.ts
- packages/libuild-plugin-swc/src/es5.ts
- packages/libuild-plugin-swc/src/index.ts
- packages/libuild-plugin-swc/src/legacy.ts
- packages/libuild-plugin-swc/src/transform.ts
- packages/libuild-plugin-swc/src/umd.ts
- packages/libuild-plugin-swc/src/utils.ts
- packages/libuild/src/bundler/index.ts
- packages/libuild/src/config/normalize.ts
- packages/libuild/src/constants/plugins.ts
- packages/libuild/src/types/config/index.ts
- tests/configs/src/__snapshots__/config.test.ts.snap
- tests/fixture/src/target/__snapshots__/target.test.ts.snap
- tests/plugins/package.json
- tests/plugins/src/swc/__snapshots__/swc.test.ts.snap
- tests/plugins/src/swc/index.tsx
- tests/plugins/src/swc/swc.test.ts
> feat: add swc transform plugin

- common/changes/@modern-js/libuild-plugin-swc/fix-swc_2023-04-24-08-49.json
- packages/libuild-plugin-swc/src/es5.ts
- packages/libuild-plugin-swc/src/legacy.ts
- packages/libuild-plugin-swc/src/transform.ts
- packages/libuild-plugin-swc/src/umd.ts
- packages/libuild-utils/src/resolvePathAndQuery.ts
> fix: change swc's jsc.parser.syntax with a reasonable value

- common/changes/@modern-js/libuild-plugin-babel-preset/fix-es5-transform_2023-05-08-08-53.json
- common/changes/@modern-js/libuild-plugin-babel/fix-es5-transform_2023-05-08-08-53.json
- common/changes/@modern-js/libuild-plugin-node-polyfill/fix-es5-transform_2023-05-08-08-53.json
- common/changes/@modern-js/libuild-plugin-svgr/fix-es5-transform_2023-05-08-08-53.json
- common/changes/@modern-js/libuild-plugin-swc/fix-es5-transform_2023-05-08-08-53.json
- common/changes/@modern-js/libuild/fix-es5-transform_2023-05-08-08-44.json
- common/changes/@modern-js/libuild/fix-es5-transform_2023-05-08-08-53.json
- common/config/rush/version-policies.json
- packages/libuild-plugin-babel-preset/CHANGELOG.json
- packages/libuild-plugin-babel-preset/CHANGELOG.md
- packages/libuild-plugin-babel-preset/package.json
- packages/libuild-plugin-babel/CHANGELOG.json
- packages/libuild-plugin-babel/CHANGELOG.md
- packages/libuild-plugin-babel/package.json
- packages/libuild-plugin-node-polyfill/CHANGELOG.json
- packages/libuild-plugin-node-polyfill/CHANGELOG.md
- packages/libuild-plugin-node-polyfill/package.json
- packages/libuild-plugin-svgr/CHANGELOG.json
- packages/libuild-plugin-svgr/CHANGELOG.md
- packages/libuild-plugin-svgr/package.json
- packages/libuild-plugin-swc/CHANGELOG.json
- packages/libuild-plugin-swc/CHANGELOG.md
- packages/libuild-plugin-swc/package.json
- packages/libuild/CHANGELOG.json
- packages/libuild/CHANGELOG.md
- packages/libuild/package.json
- packages/libuild/src/bundler/index.ts
> fix(libuild): fix exist es6 syntax in es5 and swc transform

- common/changes/@modern-js/libuild/bump_esbuild_0606_2023-06-06-07-46.json
- common/config/rush/pnpm-lock.yaml
- packages/libuild/package.json
> chore(deps): bump esbuild to 0.17.19

- common/changes/@modern-js/libuild-plugin-swc/feat-swc-transform-useDefineForClassFields_2023-06-14-06-01.json
- packages/libuild-plugin-swc/src/transform.ts
> feat(libuild-plugin-swc): support useDefineForClassFields option

- common/changes/@modern-js/libuild/feat-global-pkg-compatible-code_2023-06-20-06-15.json
- packages/libuild/src/bundler/adapter.ts
- tests/fixture/src/assets/__snapshots__/asset.test.ts.snap
- tests/fixture/src/globals/__snapshots__/globals.test.ts.snap
> feat(libuild): change compatible code for global pkg in umd mode

- common/changes/@modern-js/libuild/fix-watch-node-modules_2023-07-03-06-32.json
- packages/libuild/src/plugins/watch.ts
> fix: watch node modules

- common/changes/@modern-js/libuild-plugin-swc/chore-update-swc-plugins-0.5.0_2023-07-12-10-55.json
- common/config/rush/pnpm-lock.yaml
- packages/libuild-plugin-swc/package.json
- tests/fixture/src/lodash/index.test.ts
- tests/fixture/src/target/__snapshots__/target.test.ts.snap
> chore: update @modern-js/swc-plugins 0.5.0

- common/changes/@modern-js/libuild-plugin-swc/chore-update-swc-plugins-0.5.2_2023-07-25-08-58.json
- common/config/rush/pnpm-lock.yaml
- packages/libuild-plugin-swc/package.json
> chore: update @modern-js/swc-plugins 0.5.2

- common/config/rush/version-policies.json
- packages/libuild-plugin-babel-preset/CHANGELOG.json
- packages/libuild-plugin-babel-preset/CHANGELOG.md
- packages/libuild-plugin-babel-preset/package.json
- packages/libuild-plugin-babel/CHANGELOG.json
- packages/libuild-plugin-babel/CHANGELOG.md
- packages/libuild-plugin-babel/package.json
- packages/libuild-plugin-node-polyfill/CHANGELOG.json
- packages/libuild-plugin-node-polyfill/CHANGELOG.md
- packages/libuild-plugin-node-polyfill/package.json
- packages/libuild-plugin-svgr/CHANGELOG.json
- packages/libuild-plugin-svgr/CHANGELOG.md
- packages/libuild-plugin-svgr/package.json
- packages/libuild-plugin-swc/CHANGELOG.json
- packages/libuild-plugin-swc/CHANGELOG.md
- packages/libuild-plugin-swc/package.json
- packages/libuild/CHANGELOG.json
- packages/libuild/CHANGELOG.md
- packages/libuild/package.json
> chore: bump: 0.14.2

- common/changes/@modern-js/libuild/tests-rebase-url_2023-07-28-09-19.json
- packages/libuild/test/unit/style/less/variable.less
- packages/libuild/test/unit/style/rebaseUrl.test.ts
> test(libuild): add variable test for rebaseUrl func

- common/changes/@modern-js/libuild-plugin-swc/swc_version_0802_2023-08-02-04-12.json
- common/config/rush/pnpm-lock.yaml
- packages/libuild-plugin-swc/package.json
> fix: bump swc-plugins 0.5.5 to fix pnpm engine issue
